server:
  port: 5001
spring:
  application:
    name: springcloud-config
  cloud:
    config:
      server:
        git: # 远程库的git地址
          uri: https://github.com/zhangruibin/springcloud-config.git