server:
  port: 8012

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/,http://127.0.0.1:9002/eureka/
feign:
  hystrix:
    enabled: true #此处关于hystrix的配置一定要配置上，否则Feign的FallBack设置无效
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
spring:
  application:
    name: consumer-product-feign